services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: diviTrack

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - database
    env_file:
      - ./backend/.env

